#! /bin/bash

set -e

basename=backend/otsv
ca_key=$basename-ca-key.pem
ca_cert=$basename-ca-cert.pem
key=$basename-key.pem
cert=$basename-cert.pem

distinguished_name=$(cat <<-EOF
    [distinguished_name]
    countryName = AT
    stateOrProvinceName = ST
    localityName = Graz
    organizationName = Andreas Grünbacher
    commonName = TrialInfo
    emailAddress = auswertung@otsv.at
EOF
)

ca_config=$(cat <<-EOF
    [req]
    distinguished_name = distinguished_name
    x509_extensions = req_exts
    utf8 = yes
    prompt = no

    [req_exts]
    basicConstraints = CA:TRUE
    keyUsage = critical, keyCertSign, cRLSign

    $(echo "$distinguished_name")
EOF
)

config=$(cat <<-EOF
    [req]
    distinguished_name = distinguished_name
    req_extensions = req_exts
    utf8 = yes
    prompt = no

    $(echo "$distinguished_name")

    [req_exts]
    keyUsage = digitalSignature, keyEncipherment
    extendedKeyUsage = serverAuth
    subjectAltName = @alternate_names

    [alternate_names]
    IP.1 = 127.0.0.1
    IP.2 = ::1
    DNS.1 = localhost
    DNS.2 = localhost.localdomain
    DNS.3 = *.otsv.at
EOF
)

die() {
    echo "$*"
    exit 1
}

if [ -e "$ca_key" -o -e "$ca_cert" ]; then
    [ -e "$ca_key" ] || die "File $ca_key is missing"
    [ -e "$ca_cert" ] || die "File $ca_cert is missing"
    echo "Files $ca_key and $ca_cert exist"
else
    openssl req \
	-config <(echo "$ca_config") \
	-x509 \
	-nodes \
	-newkey rsa:4096 \
	-sha256 \
	-days 36500 \
	-keyout "$ca_key" \
	-out "$ca_cert"
fi

if [ -e "$key" -o -e "$cert" ]; then
    [ -e "$key" ] || die "File $key is missing"
    [ -e "$cert" ] || die "File $cert is missing"
    echo "Files $key and $cert exist"
else
    csr=$(mktemp)
    cleanup() {
	rm -f "$csr"
    }
    trap cleanup EXIT

    openssl req \
	-config <(echo "$config") \
	-nodes \
	-newkey rsa:4096 \
	-sha256 \
	-days 36500 \
	-keyout "$key" \
	-out "$csr"

    openssl x509 \
	-req \
	-days 36500 \
	-in "$csr" \
	-extensions req_exts \
	-extfile <(echo "$config") \
	-CA "$ca_cert" \
	-CAkey "$ca_key" \
	-set_serial 1 \
	-out "$cert"
fi
