#! /bin/sh

set -e

update=trialinfo-update-$(date +%Y-%m-%d)

blocks=$(( ($(stat -c '%s' trialinfo-update.in) + 511) / 512 ))

rm -f $update
sed -e "s:@BLOCKS@:$blocks:g" trialinfo-update.in > $update

git bundle create $update.bundle nb2016..otsv
dd if=$update.bundle of=$update bs=512 seek=$blocks status=none
rm -f $update.bundle

chmod +x $update
set -- $(wc -c $update)
echo "$update created ($1 bytes)"
